# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temperature_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'temperature_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19temperature_service.proto\x12\x13temperature_service\"\x07\n\x05\x45mpty\"\x1d\n\x08SensorId\x12\x11\n\tsensor_id\x18\x01 \x01(\t\"C\n\x0cHistoryQuery\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x10\n\x08\x66rom_iso\x18\x02 \x01(\t\x12\x0e\n\x06to_iso\x18\x03 \x01(\t\"\xab\x01\n\x14TemperatureAggregate\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tsensor_id\x18\x02 \x01(\t\x12\x18\n\x10window_start_iso\x18\x03 \x01(\t\x12\x16\n\x0ewindow_end_iso\x18\x04 \x01(\t\x12\x13\n\x0b\x61vg_celsius\x18\x05 \x01(\x01\x12\x14\n\x0csample_count\x18\x06 \x01(\x05\x12\x17\n\x0f\x63omputed_at_iso\x18\x07 \x01(\t\"T\n\x18TemperatureAggregateList\x12\x38\n\x05items\x18\x01 \x03(\x0b\x32).temperature_service.TemperatureAggregate2\xb5\x02\n\x10TemperatureQuery\x12^\n\x12GetLatestAggregate\x12\x1d.temperature_service.SensorId\x1a).temperature_service.TemperatureAggregate\x12\x61\n\x14ListLatestAggregates\x12\x1a.temperature_service.Empty\x1a-.temperature_service.TemperatureAggregateList\x12^\n\nGetHistory\x12!.temperature_service.HistoryQuery\x1a-.temperature_service.TemperatureAggregateListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'temperature_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=50
  _globals['_EMPTY']._serialized_end=57
  _globals['_SENSORID']._serialized_start=59
  _globals['_SENSORID']._serialized_end=88
  _globals['_HISTORYQUERY']._serialized_start=90
  _globals['_HISTORYQUERY']._serialized_end=157
  _globals['_TEMPERATUREAGGREGATE']._serialized_start=160
  _globals['_TEMPERATUREAGGREGATE']._serialized_end=331
  _globals['_TEMPERATUREAGGREGATELIST']._serialized_start=333
  _globals['_TEMPERATUREAGGREGATELIST']._serialized_end=417
  _globals['_TEMPERATUREQUERY']._serialized_start=420
  _globals['_TEMPERATUREQUERY']._serialized_end=729
# @@protoc_insertion_point(module_scope)
