# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import temperature_service_pb2 as temperature__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in temperature_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TemperatureQueryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLatestAggregate = channel.unary_unary(
                '/temperature_service.TemperatureQuery/GetLatestAggregate',
                request_serializer=temperature__service__pb2.SensorId.SerializeToString,
                response_deserializer=temperature__service__pb2.TemperatureAggregate.FromString,
                _registered_method=True)
        self.ListLatestAggregates = channel.unary_unary(
                '/temperature_service.TemperatureQuery/ListLatestAggregates',
                request_serializer=temperature__service__pb2.Empty.SerializeToString,
                response_deserializer=temperature__service__pb2.TemperatureAggregateList.FromString,
                _registered_method=True)
        self.GetHistory = channel.unary_unary(
                '/temperature_service.TemperatureQuery/GetHistory',
                request_serializer=temperature__service__pb2.HistoryQuery.SerializeToString,
                response_deserializer=temperature__service__pb2.TemperatureAggregateList.FromString,
                _registered_method=True)


class TemperatureQueryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLatestAggregate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLatestAggregates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TemperatureQueryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLatestAggregate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestAggregate,
                    request_deserializer=temperature__service__pb2.SensorId.FromString,
                    response_serializer=temperature__service__pb2.TemperatureAggregate.SerializeToString,
            ),
            'ListLatestAggregates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLatestAggregates,
                    request_deserializer=temperature__service__pb2.Empty.FromString,
                    response_serializer=temperature__service__pb2.TemperatureAggregateList.SerializeToString,
            ),
            'GetHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistory,
                    request_deserializer=temperature__service__pb2.HistoryQuery.FromString,
                    response_serializer=temperature__service__pb2.TemperatureAggregateList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'temperature_service.TemperatureQuery', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('temperature_service.TemperatureQuery', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TemperatureQuery(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLatestAggregate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/temperature_service.TemperatureQuery/GetLatestAggregate',
            temperature__service__pb2.SensorId.SerializeToString,
            temperature__service__pb2.TemperatureAggregate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLatestAggregates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/temperature_service.TemperatureQuery/ListLatestAggregates',
            temperature__service__pb2.Empty.SerializeToString,
            temperature__service__pb2.TemperatureAggregateList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/temperature_service.TemperatureQuery/GetHistory',
            temperature__service__pb2.HistoryQuery.SerializeToString,
            temperature__service__pb2.TemperatureAggregateList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
